### PR TITLE
Fix for #4662 and added util scripts that allowed to detect the issue

### LINKED ISSUE #4662: Unable to remove approval criteria from CLA Corporate Console
## Summary

Currently organizations are not able to remove approval criteria in the CLA Corporate Console (https://organization.lfx.linuxfoundation.org/)

## Background

CLA Managers are able to add approval criteria without issues, but removing the API call fails with:
```
{
    "errors": [
        {
            "message": "Cannot return null for non-nullable field ApprovalListResult.message.",
            "locations": [
                {
                    "line": 6,
                    "column": 5
                }
            ],
            "path": [
                "updateApprovalList",
                "message"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "Error: Cannot return null for non-nullable field ApprovalListResult.message.",
                        "    at completeValue (/usr/src/app/node_modules/graphql/execution/execute.js:605:13)",
                        "    at executeField (/usr/src/app/node_modules/graphql/execution/execute.js:500:19)",
                        "    at executeFields (/usr/src/app/node_modules/graphql/execution/execute.js:414:22)",
                        "    at completeObjectValue (/usr/src/app/node_modules/graphql/execution/execute.js:925:10)",
                        "    at completeValue (/usr/src/app/node_modules/graphql/execution/execute.js:646:12)",
                        "    at /usr/src/app/node_modules/graphql/execution/execute.js:497:9",
                        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                        "    at async execute (/usr/src/app/node_modules/apollo-server-core/dist/requestPipeline.js:207:20)",
                        "    at async processGraphQLRequest (/usr/src/app/node_modules/apollo-server-core/dist/requestPipeline.js:150:28)",
                        "    at async processHTTPRequest (/usr/src/app/node_modules/apollo-server-core/dist/runHttpQuery.js:222:30)"
                    ]
                }
            }
        }
    ],
    "data": {
        "updateApprovalList": null
    }
}
```
Payload:
```
{"operationName":"updateApprovalList","variables":{"input":{"companyId":"326d5582-5ce9-4ff4-8cc3-a2fcf865c39c","projectId":"a092M00001IdwOGQAZ","claGroupId":"31032d86-31c9-49dd-8478-63ffa6af47b6","approvalListPayload":{"AddDomainApprovalList":[],"RemoveDomainApprovalList":[],"AddEmailApprovalList":[],"RemoveEmailApprovalList":["jarias@nec.com"],"AddGithubOrgApprovalList":[],"RemoveGithubOrgApprovalList":[],"AddGithubUsernameApprovalList":[],"RemoveGithubUsernameApprovalList":[],"AddGitlabOrgApprovalList":[],"RemoveGitlabOrgApprovalList":[],"AddGitlabUsernameApprovalList":[],"RemoveGitlabUsernameApprovalList":[]}}},"query":"mutation updateApprovalList($input: ApprovalListInput!) {\n  updateApprovalList(input: $input) {\n    code\n    approvalList\n    success\n    message\n    __typename\n  }\n}\n"}
```

Confirmed the issue in different organizations in production. Please note this issue is critical for security organizations that uses the auto-ecla feature.

## Expected behavior

CLA Manager should be able to remove approval criteria.

## Screenshots

Image

### PR DESCRIPTION
**Pull request by lukaszgryglicki**
[Slack investigation](https://linuxfoundation.slack.com/archives/C0697E1QHNG/p1747120228768239?thread_ts=1747069401.098099&cid=C0697E1QHNG).

cc @mlehotskylf @jarias-lfx @thakurveerendras 

Fixes #4662

### CODE REVIEW

File: cla-backend-go/signatures/repository.go [hunk 1]
```diff
@@ -3214,9 +3214,9 @@ func (repo repository) UpdateApprovalList(ctx context.Context, claManager *model
 	var gerritICLAECLAs []string
 
 	// Only load the gerrit user information, which is costly, if we have updates to remove email or email domains
-	if (params.RemoveEmailApprovalList != nil && len(params.RemoveEmailApprovalList) > 0) || (params.RemoveDomainApprovalList != nil && len(params.RemoveDomainApprovalList) > 0) {
+	if len(params.RemoveEmailApprovalList) > 0 || len(params.RemoveDomainApprovalList) > 0 {
 
-		goRoutines := 2
+		goRoutines := 0
```
Comment (lukaszgryglicki) [inline cla-backend-go/signatures/repository.go:3219]: This is the critical fix @jarias-lfx @mlehotskylf

**Review by mlehotskylf — APPROVED** [review]
